config/routes.rb
DanceDynamics::Application.routes.draw do

  devise_for :users, :controllers => { 
    :registrations => "users/registrations" ,
    :omniauth_callbacks => "omniauth_callbacks"
  }
  devise_scope :user do
    get '/sign_in' => 'sessions#new'
    get "/sign_up", :to => "registrations#new"
  end

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  mount Monologue::Engine, at: '/blog'

 
  get "home/index"
  get "/dashboard" => "users#dashboard", :as => :user_dashboard
  get "/dashboard/profile" => "users#profile", :as => :user_profile
  get "/dashboard/my_classes"  => "users#my_classes", :as => :user_my_classes
  get "users/billing"
  put "users/update_avatar"
  get "users/edit_payment_info"
  get "users/confirm_payment_info"
  get "/register" => "users#new_membership", :as => :new_membership
  post "/payment" => "users#create_membership", :as => :create_membership
  get "users/new_subscription_method"
  get "home/subscription"
  
  resources :styles, :levels, :favorite_videos, :history_videos, :teachers
  resources :favorite_teachers, :only => [:create, :destroy]
  resources :users do
    resources :addresses
    resources :credit_cards
    resources :subscriptions
     post "credit_cards/make_default"
  end
  
  namespace :admin do
    root :to => "admin#index"
    get "/plans" => "admin#plans", :as => :admin_plans do 
      resources :subscriptions
    end
    resources :users
    get "new_admin" => "users#new_admin", :as => :new_admin
    post "create_admin" => "users#create_admin", :as => :create_admin
    get "edit_admin/:id" => "users#edit_admin", :as => :edit_admin
    put "update_admin/:id" => "users#update_admin", :as => :update_admin
    get "new_customer" => "users#new_customer", :as => :new_customer
    post "create_customer" => "users#create_customer", :as => :create_customer
    get "edit_customer/:id" => "users#edit_customer", :as => :edit_customer
    put "update_customer/:id" => "users#update_customer", :as => :update_customer
    resources :videos, :except => [:index]
    resources :today_videos
    get "videos" => "videos#index_admin", :as => :admin_videos
    resources :levels
    resources :styles
    resources :teachers
    resources :users
    resources :comments
    put "/approve_comments" => "comments#approve_comments", :as => :approve_comments
  end
  resources :credit_card_info, :only => [:edit]

  resources :videos do
    resources :comments
  end

  match 'users/confirm_payment_info' => 'users#confirm_payment_info', :as => :confirm_payment_info
  match 'dashboard/billing', :to => 'users#billing'
  match 'credit_card_info/confirm' => 'credit_card_info#confirm', :as => :confirm_credit_card_info
  match 'subscription', :to => 'home#subscription'

  root :to => 'home#index'

end

app/views/admin/_admin_dashboard_tabs.html.erb
<div class="clearfix admin_dashboard_tabs" id="dashboard_tabs">
  <div class="inner_container">
    <ul class="clearfix">
      <li class="<%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-home"></i><span>Dashboard</span>') %>
          <%= link_to link, admin_root_path, :class => 'dashboard' %>
      </li>
      <li class="<%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-user"></i><span>Users</span>') %>
          <%= link_to link, admin_users_path, :class => 'users' %>
      </li>
      <li class="<%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-comment"></i><span>Comments</span>') %>
          <%= link_to link, admin_comments_path, :class => 'comments' %>
      </li>
      <li class="<%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-briefcase"></i><span>Plans</span>') %>
          <%= link_to link, admin_admin_plans_path, :class => 'plans' %>
      </li>
      <li class="<%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-film"></i><span>Videos</span>') %>
          <%= link_to link, admin_videos_path, :class => 'videos' %>
      </li>
      <li class="<%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-music"></i><span>Styles</span>') %>
          <%= link_to link, admin_styles_path, :class => 'styles' %>
      </li>
      <li class="<%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-stats"></i><span>Levels</span>') %>
          <%= link_to link, admin_levels_path, :class => 'levels' %>
        </li>
        <li class="last <%= active_tab %>">
          <% link = raw('<i class="glyphicon glyphicon-tower"></i><span>Teachers</span>') %>
          <%= link_to link, admin_teachers_path, :class => 'teachers' %>
        </li>
    </ul>
  </div>
</div>

app/views/admin/index.html.erb
<%= render 'admin_dashboard_tabs', :active_tab => 'dashboard' %>
<div id="dashboard_section" class="admin_dashboard">
  <div class="inner_container">
    <div id="tabs-1">
      	<h2>Welcome, <span class="text-primary"><%= current_user.username %></span></h2>
      	<table class="table table-condensed table-striped">
      		<tr>
      			<th>Id</th>
      			<th>Username</th>
      			<th>Email</th>
      			<th>Created at</th>
      			<th>Membership status</th>
      			<th>Subscription type</th>
      			<th></th>
      		</tr>
      		<% @users.each do |user| %>
	      		<tr>
	      			<td><%= user.id %></td>
	      			<td><%= user.email %></td>
	      			<td><%= user.username %></td>
	      			<td><%= nice_date_form(user.created_at) %></td>
	      			<td><%= user.id %></td>
	      			<td><%= user.id %></td>
	      			<td>
	      				<%= link_to "View", "", :class => "btn btn-success btn-sm" %>
	      				<%= link_to "Edit", "", :class => "btn btn-warning btn-sm" %>
	      				<%= link_to "Delete", "", :class => "btn btn-danger btn-sm" %>
	      			</td>
	      		</tr>
      		<% end%>
      	</table>
	</div>
  </div>
</div>