config/routes.rb
DanceDynamics::Application.routes.draw do

  devise_for :users, :controllers => { 
    :registrations => "users/registrations" ,
    :omniauth_callbacks => "omniauth_callbacks"
  }
  devise_scope :user do
    get '/sign_in' => 'sessions#new'
    get "/sign_up", :to => "registrations#new"
  end

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  mount Monologue::Engine, at: '/blog'

 
  get "home/index"
  get "/dashboard" => "users#dashboard", :as => :user_dashboard
  get "/dashboard/profile" => "users#profile", :as => :user_profile
  get "/dashboard/my_classes"  => "users#my_classes", :as => :user_my_classes
  get "users/billing"
  put "users/update_avatar"
  get "users/edit_payment_info"
  get "users/confirm_payment_info"
  get "/register" => "users#new_membership", :as => :new_membership
  post "/payment" => "users#create_membership", :as => :create_membership
  get "users/new_subscription_method"
  get "home/subscription"
  
  resources :styles, :levels, :favorite_videos, :history_videos, :teachers
  resources :favorite_teachers, :only => [:create, :destroy]
  resources :users do
    resources :addresses
    resources :credit_cards
    resources :subscriptions
     post "credit_cards/make_default"
  end
  
  namespace :admin do
    root :to => "admin#index"
    get "/plans" => "admin#plans", :as => :admin_plans do 
      resources :subscriptions
    end
    resources :users
    get "new_admin" => "users#new_admin", :as => :new_admin
    post "create_admin" => "users#create_admin", :as => :create_admin
    get "edit_admin/:id" => "users#edit_admin", :as => :edit_admin
    put "update_admin/:id" => "users#update_admin", :as => :update_admin
    get "new_customer" => "users#new_customer", :as => :new_customer
    post "create_customer" => "users#create_customer", :as => :create_customer
    get "edit_customer/:id" => "users#edit_customer", :as => :edit_customer
    put "update_customer/:id" => "users#update_customer", :as => :update_customer
    resources :videos, :except => [:index]
    resources :today_videos
    get "videos" => "videos#index_admin", :as => :admin_videos
    resources :levels
    resources :styles
    resources :teachers
    resources :users
    resources :comments
    put "/approve_comments" => "comments#approve_comments", :as => :approve_comments
  end
  resources :credit_card_info, :only => [:edit]

  resources :videos do
    resources :comments
  end

  match 'users/confirm_payment_info' => 'users#confirm_payment_info', :as => :confirm_payment_info
  match 'dashboard/billing', :to => 'users#billing'
  match 'credit_card_info/confirm' => 'credit_card_info#confirm', :as => :confirm_credit_card_info
  match 'subscription', :to => 'home#subscription'

  root :to => 'home#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :description,
					  :duration, 
					  :style_id, 
					  :teacher_id,
					  :level_id, 
					  :title,
					  :photo,
					  :wistia_id

	has_attached_file :photo, { 
				:styles => {:medium => "400x400>", :small => "150x150>" },
				:default_url => "http://pixelholdr.com/color:ff5c23/350x246"
				}.merge(PAPERCLIP_STORAGE_OPTIONS)
	            
	# validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg','image/jpg', 'image/png']

	validates_presence_of :description, :duration, :style_id, :teacher_id, :level_id, :title, :wistia_id 

	#relationships
	has_many :comments, dependent: :destroy
	has_many :today_videos, dependent: :destroy
	belongs_to :teacher
	belongs_to :style
	belongs_to :level

	# Favorited by users
	has_many :favorite_videos, dependent: :destroy # just the 'relationships'
	has_many :favorited_by, through: :favorite_videos, source: :user # the actual users favoriting a video
	# Favorited by users
	has_many :history_videos, dependent: :destroy # just the 'relationships'
	has_many :historied_by, through: :history_videos, source: :user # the actual users finish watching a video 

	def calendar
	    @videos = Video.all
	end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_filter :authenticate_admin_user!
 def index_admin
    @search = Video.search(params[:q])
    @videos = @search.result

    @today_video = TodayVideo.new

    @todays = TodayVideo.all
    @videos_by_date = @todays.group_by(&:set_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

  end


  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

   # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to admin_videos_path, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to admin_videos_path, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to admin_videos_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :membership_required

  # GET /videos
  # GET /videos.json
  def index
  # @videos = Video.page(params[:page]).per_page(3)

   @q = Video.search(params[:q])
   @videos = @q.result(distinct: true).page(params[:page]).per_page(3)
   @level_value = ["1","2","3"]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
      format.js
      #  do
      #   @loaded_video = render
      # end
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
    @popular = FavoriteVideo.most_favorite_videos
    @latest_comments = Comment.latest_comment
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
	def get_favorite_video(id)
		@popular_videos = Video.find(id)
		return @popular_videos
	end

	def calendar(date = Date.today, &block)
	    Calendar.new(self, date, block).table
	end

	class Calendar < Struct.new(:view, :date, :callback)
	    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
	    START_DAY = :sunday

	    delegate :content_tag, to: :view

	    def table
	      content_tag :table, class: "calendar" do
	        header + week_rows
	      end
	    end

	    def header
	      content_tag :tr do
	        HEADER.map { |day| content_tag :th, day }.join.html_safe
	      end
	    end

	    def week_rows
	      weeks.map do |week|
	        content_tag :tr do
	          week.map { |day| day_cell(day) }.join.html_safe
	        end
	      end.join.html_safe
	    end

	    def day_cell(day)
	      content_tag :td, view.capture(day, &callback), class: day_classes(day)
	    end

	    def day_classes(day)
	      classes = []
	      classes << "today selected" if day == Date.today
	      classes << "disabled_days disabled" if day < Date.today
	      classes << "notmonth" if day.month != date.month
	      classes.empty? ? nil : classes.join(" ")
	    end

	    def weeks
	      first = date.beginning_of_month.beginning_of_week(START_DAY)
	      last = date.end_of_month.end_of_week(START_DAY)
	      (first..last).to_a.in_groups_of(7)
	    end
	end
end

app/views/videos/_add_favorites_button.html.erb
<% if current_user %>
  <div class="favorite_button_container clearfix">
    <% if current_user.favorites.include? @video %>
      <%= render 'videos/unfavorite' %>
    <% else %>
      <%= render 'videos/favorite' %>
    <% end %>
  </div>
<% end %>

app/views/videos/_favorite.html.erb
<%= link_to (raw('<span class="glyphicon glyphicon-star"></span><span class="txt">Add to favorites</span>')), favorite_videos_path(:video_id => @video), { method: :post, :class => "btn buy add_favorites pull-right", remote: true }  %>

app/views/videos/_form.html.erb
<div class="inner_container">
    <%= form_for(@video, :html => { :class => 'form-horizontal'}) do |f| %>
      <% if @video.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

          <ul>
          <% @video.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title, :class => "col-lg-2 control-label" %>
        <div class="col-lg-7">
          <%= f.text_field :title, :autofocus => true, :class => "form-control", :placeholder => "Video title" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :duration, :class => "col-lg-2 control-label" %>
        <div class="col-lg-7">
          <%= f.text_field :duration, :class => "form-control", :placeholder => "Duration" %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Select Style</label>
        <div class="col-lg-7">
          <%= select("video", "style_id", Style.all.collect {|p| [ p.name, p.id ] }, {prompt:'Select Style Type'}, :class => "form-control" )%>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Select Teacher</label>
        <div class="col-lg-7">
          <%= f.collection_select( :teacher_id, Teacher.order(:name), :id, :name, {:prompt => "Select a teacher"}, { :class => "form-control"}) %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Select Level</label>
        <div class="col-lg-7">
          <%= f.collection_select( :level_id, Level.order(:name), :id, :name, {:prompt => "Select a level"}, { :class => "form-control"}) %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Enter Wistia video code</label>
        <div class="col-lg-7">
          <%= f.text_field :wistia_id, :class => "form-control", :placeholder => "wistia id" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :photo, :class => "col-lg-2 control-label" %>
        <div class="col-lg-7">
          <%= f.file_field :photo, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, :class => "col-lg-2 control-label" %>
        <div class="col-lg-7">
          <%= f.text_area :description, :class => "form-control", :placeholder => "Description of the video", :rows => "10" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-7">
          <%= link_to "Go back", admin_videos_path, :class => "btn btn-default"%>
          <%= f.submit :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div><!--/inner-container-->
</div><!--/gray-box-->

app/views/videos/_latest_comments.html.erb
<h3 class="video_title">Latest Comments</h3>
<div class="latest_comments_box">
	<ul class="latest_comment_list">
		<% @latest_comments.where(:approved => [true,nil]).each do |c| %>  
	    	<li>
	    		<p><b><%= link_to c.user.username, c.user %></b> said on <%= link_to c.video.title, c.video %></p>
	    		<p><span class="glyphicon glyphicon-chevron-right"></span><%= c.comment_text %></p>
	    	</li>
	    <% end %>
	</ul>
</div>

app/views/videos/_popular_videos.html.erb
<h3 class="video_title">Most favorited Videos</h3>
<div class="favorite_videos_box">
  <ul>
    <% @popular.each do |popular| %>
        <% @popular_videos = get_favorite_video(popular.video_id) %>
        <li class="favorite_videos">
        <ul class="favorite_videos_list clearfix">
          <li class="favorite_video_img">
            <% image = image_tag @popular_videos.photo.url(:small) %>
            <%= link_to image, popular.video %>
          </li>
          <li class="favorite_video_content">
            <h4><%= link_to @popular_videos.title, popular.video %></h4>
            <p><%= link_to @video.style.name, @video.style %> | by <%= link_to @video.teacher.name, @video.teacher %></p>
          </li>
        </ul>  
      </li>
    <% end %>
  </ul>
</div> 

app/views/videos/_sorted_videos.html.erb
<%= render @videos %>
<%= will_paginate @videos %>

app/views/videos/_unfavorite.html.erb
<%= link_to (raw('<span class="glyphicon glyphicon-star"></span><span class="txt">Remove favorites</span>')), favorite_video_path( @video, :video_id => @video.id), { method: :delete, :class => "btn buy remove_favorites pull-right", remote: true } %>

app/views/videos/_video.html.erb
<div class="col-lg-4">
  <div class="video_container">
    <div class="video_item">
      <%= image_tag(video.photo.url(:medium), :alt => video.title, :class => "video_thumb") %>
      <div class="video_overlay">
        <%= link_to ( image_tag "play_button.png" ), video, 
              :id => "video#{video.id}",
              :class => "video_popover",
              :data => {:toggle => "popover",
                        :trigger => "hover",
                        :content => "<h2>#{video.title}</h2>
                        <p class='style'><b>Style:</b>#{video.style.name}</p>
                        <p class='teacher'><b>Teacher:</b>#{video.teacher.name}</p>
                        <p class='level'><b>Level:</b>#{video.level}</p>
                        <hr/>
                        <p class='desc'>#{video.description}</p>"} 
        %>
        <div class="video_duration"><span><%= video.duration %> min</span></div>
      </div><!--/video_overlay--> 
    </div> <!--/video_item-->
    <div class="video_short_content">
      <div class="video_content_inner">
        <div class="video_level">
          <% x = 1 %>
            <% while x <= video.level.scale %>
              <% x+=1 %>
              <span class="glyphicon glyphicon-leaf"></span>
            <% end %>
        </div>
        <p>by <%= link_to video.teacher.name, video.teacher %></p>
        <div class="social clearfix">
          <ul class="no_list left_list">
            <li>
              <span class="txt">
                <%= FavoriteVideo.count :conditions => {:video_id => video.id} %>
              </span>
              <span class="glyphicon glyphicon-heart"></span>
            </li>
            <li>
              <span class="txt"><%= video.comments.count %> </span>
              <span class="glyphicon glyphicon-comment"></span>
            </li>
            <li> | </li>
            <li><%= link_to video.style.name, video.style %></li>
          </ul>
        </div>
        <h2 class="clearfix"><%= link_to video.title, video %></h2>
        <p>
          <%= (truncate h(video.description), 
                  :length => 220, 
                  :omission => "... #{link_to'more',video}")
                  .html_safe %>
        </p>
      </div><!--/video_content_inner-->
    </div><!--/video_short_content-->
  </div><!--/video_container-->
</div><!--/col-lg-4-->
<div id="test"></div>

app/views/videos/edit.html.erb
<%= render 'admin/admin_dashboard_tabs', :active_tab => 'dashboard' %>
<div id="dashboard_section" class="admin_dashboard admin_style">
  <div class="inner_container">
    <div id="tabs-1">
      	<h2> Edit <%= @video.title %></h2>
      	<hr/>
      	<div class="row clearfix">
      		<div class="col-lg-8">
      			<%= render 'form' %>
      		</div>
      	</div>
	</div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="display_videos_module">
    <h1>Listing videos</h1>
      
      <%= link_to "Filter Classes",:id => "class_filter" %>

      <%= search_form_for(@q, :html => { :class => 'form-inline clearfix', :id => 'video_search_form', :remote =>true}) do |f| %>
        <div class="well search_dark">
          <table class="table table-responsive">
            <tr>
              <th><%= f.label :title_cont,"Search Videos:" %></th>
              <th><%= f.label :style_id_eq, "Select Style" %></th>
              <th><%= f.label :teacher_id_eq, "Select Teacher" %></th>
              <th><label>Select Duration</label></th>
              <th></th>
              <th><label>Select Level</label></th>
            </tr>
            <tr>
              <td><%= f.text_field :title_cont, :class => "form-control", :placeholder => "Search Video" %></td>
              <td><%= f.collection_select( :style_id_eq, Style.order(:name), :id, :name, {:prompt => "Select a style"}, { :class => "form-control"}) %></td>
              <td><%= f.collection_select( :teacher_id_eq, Teacher.order(:name), :id, :name, {:prompt => "Select a teacher"}, { :class => "form-control"}) %></td>
              <td>
                <div class="duration_slider"></div> 
                <%= f.hidden_field :duration_lteq, :id =>"duration_hidden" %>
              </td>
              <td><p class="duration_min"><span id="duration_slider_result">120</span> min</p></td>
              <td class="level">
                <% @level_value.each do |d| %>
                  <input type="checkbox" name="q[level_eq_any][]" id="level_eq_any_<%= d %>" class="level_eq_search" value="<%= d %>"/>
                  <label for="level_eq_any_<%= d %>">
                    <% x = 1 %>
                    <% while x <= d.to_i %>
                    <% x+=1 %>
                    <span class="glyphicon glyphicon-leaf"></span>
                    <% end %>
                  </label>
                <% end %>
                
                
              </td>
            </tr>
          </table>
        </div><!--/well-->
        <div class="row clearfix" id="video_listing">
          <%= render 'sorted_videos' %>
        </div><!--/row-->

        <%= f.submit 'Search', :class => "search_submit" %>
      <% end %>

<% if user_signed_in? %>
    <p><%= link_to 'New Video', new_video_path %></p>
<% end %>
</div><!--/videos_module-->

app/views/videos/index.js.erb
<% if params[:page] %>
	loading_videos = '<%= escape_javascript(render("sorted_videos")) %>';
	$('#video_listing').find('.pagination').remove();
	$('#video_listing').append(loading_videos);
	
  	<% if @videos.next_page %>
	  $('.pagination').replaceWith('<%= j will_paginate(@videos) %>');
	<% else %>
	  $('.pagination').remove();
	<% end %>
	<% sleep 1 %>
	
<% else %>
	$('#video_listing').html('<%= escape_javascript(render("sorted_videos")) %>');
	<% sleep 1 %>
<% end %>

app/views/videos/index_admin.html.erb
<%= render 'admin/admin_dashboard_tabs', :active_tab => 'dashboard' %>
<div id="dashboard_section" class="admin_dashboard admin_video">
  <div class="inner_container">
    <div id="tabs-1">
    	<%= link_to raw('<span class="glyphicon glyphicon-plus"></span>Add New Video'), new_admin_video_path, :class =>"btn btn-primary pull-right btn-sm add_new_style_btn"%>
      	<h2 class="">Your Listed Videos</h2>
      	<table class="table table-condensed table-striped">
      		<tr>
      			<th>Id</th>
      			<th>Name</th>
      			<th>Style</th>
      			<th>Level</th>
      			<th>Teacher</th>
      			<th>Duration</th>
      			<th>Created at</th>
      			<th>Updated at</th>
      			<th></th>
      		</tr>
      		<% @videos.each do |video| %>
	      		<tr>
	      			<td><%= video.id %></td>
	      			<td><%= video.title %></td>
	      			<td><%= video.style.name %></td>
	      			<td><%= video.level.name %></td>
	      			<td><%= video.teacher.name %></td>
	      			<td><%= video.duration %> min</td>
	      			<td><%= nice_date_form(video.created_at) %></td>
	      			<td><%= nice_date_form(video.updated_at) %></td>
	      			<td>
                <%= link_to "Delete", admin_video_path(video), :method => :delete, :confirm =>'Are you sure?', :class => "btn btn-danger btn-sm pull-right" %>
	      				<%= link_to "Edit", edit_admin_video_path(video), :class => "btn btn-warning btn-sm pull-right" %>
	      				
	      				<%= link_to "View", admin_video_path(video), :class => "btn btn-success btn-sm pull-right" %>
	      			</td>
	      		</tr>
      		<% end%>
      	</table>
	</div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="row clearfix" id="video_section">
  <div class="col-lg-9">
    <div class="video_box">
      <div class="inner_container">
        <script charset="ISO-8859-1" src="http://fast.wistia.net/static/concat/E-v1.js"></script>

        <div id="wistia_<%= @video.wistia_id %>" class="wistia_embed" style="width:100%;height:450px;" data-video-width="640" data-video-height="360" data-wistia-id="<%= @video.wistia_id %>" data-video-id="<%= @video.id %>">&nbsp;</div>

        <h2 class="video_title"><%= @video.title %></h2>
        
        <div id="video_info">
          <div class="video_sub_info">
            <div class="pull-right" id="video_social">
              <div class="favorited_by pull-right">
                <span class="txt">
                  <%= FavoriteVideo.count :conditions => {:video_id => @video.id} %>
                </span>
                <span class="glyphicon glyphicon-heart"></span>
              </div><!--/favorited_by-->

              <div class="commented_by pull-right">
                <span class="txt"><%= @video.comments.count %> </span>
                <span class="glyphicon glyphicon-comment"></span>
              </div><!--/commented_by-->

              <div class="video_level pull-right">
                <% x = 1 %>
                <span>Level: </span>
                <% while x <= @video.level.scale %>
                  <% x+=1 %>
                  <span class="glyphicon glyphicon-leaf"></span>
                <% end %>
              </div><!--video_level-->

              <div class="duration pull-right">
                <span class="txt"><%= @video.duration %> min</span>
                <span class="glyphicon glyphicon-time"></span>
              </div><!--/duration-->
            </div>
            <div>
              <%= link_to @video.style.name, @video.style %> | by <%= link_to @video.teacher.name, @video.teacher %> on <%= nice_date_form(@video.created_at )%>
            </div>
          
          </div><!--/video-sub-info-->
          <div class="video_description"><%= @video.description %></div>
        </div><!--/video_info-->        
      </div><!--/inner_container-->
    </div><!--/video_box-->

    <%= render "comments/comments_section", :selected_video => @video %>
  
  </div><!--/col-lg-9-->

  <div class="col-lg-3" id="video_sidebar">
    <% if current_user.admin? %>
      <%= link_to raw('<span class="glyphicon glyphicon-wrench"></span><span class="txt">Edit This Video</span>'), edit_admin_video_path(@video),:class =>"btn edit" %>
    <% end %>

    <%= render "add_favorites_button" %>
    <hr/>
    <%= render "popular_videos" %> 
    <hr/>
    <%= render "latest_comments" %> 
    
  </div>
</div>