config/routes.rb
DanceDynamics::Application.routes.draw do

  devise_for :users, :controllers => { 
    :registrations => "users/registrations" ,
    :omniauth_callbacks => "omniauth_callbacks"
  }
  devise_scope :user do
    get '/sign_in' => 'sessions#new'
    get "/sign_up", :to => "registrations#new"
  end

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  mount Monologue::Engine, at: '/blog'

 
  get "home/index"
  get "/dashboard" => "users#dashboard", :as => :user_dashboard
  get "/dashboard/profile" => "users#profile", :as => :user_profile
  get "/dashboard/my_classes"  => "users#my_classes", :as => :user_my_classes
  get "users/billing"
  put "users/update_avatar"
  get "users/edit_payment_info"
  get "users/confirm_payment_info"
  get "/register" => "users#new_membership", :as => :new_membership
  post "/payment" => "users#create_membership", :as => :create_membership
  get "users/new_subscription_method"
  get "home/subscription"
  
  resources :styles, :levels, :favorite_videos, :history_videos, :teachers
  resources :favorite_teachers, :only => [:create, :destroy]
  resources :users do
    resources :addresses
    resources :credit_cards
    resources :subscriptions
     post "credit_cards/make_default"
  end
  
  namespace :admin do
    root :to => "admin#index"
    get "/plans" => "admin#plans", :as => :admin_plans do 
      resources :subscriptions
    end
    resources :users
    get "new_admin" => "users#new_admin", :as => :new_admin
    post "create_admin" => "users#create_admin", :as => :create_admin
    get "edit_admin/:id" => "users#edit_admin", :as => :edit_admin
    put "update_admin/:id" => "users#update_admin", :as => :update_admin
    get "new_customer" => "users#new_customer", :as => :new_customer
    post "create_customer" => "users#create_customer", :as => :create_customer
    get "edit_customer/:id" => "users#edit_customer", :as => :edit_customer
    put "update_customer/:id" => "users#update_customer", :as => :update_customer
    resources :videos, :except => [:index]
    resources :today_videos
    get "videos" => "videos#index_admin", :as => :admin_videos
    resources :levels
    resources :styles
    resources :teachers
    resources :users
    resources :comments
    put "/approve_comments" => "comments#approve_comments", :as => :approve_comments
  end
  resources :credit_card_info, :only => [:edit]

  resources :videos do
    resources :comments
  end

  match 'users/confirm_payment_info' => 'users#confirm_payment_info', :as => :confirm_payment_info
  match 'dashboard/billing', :to => 'users#billing'
  match 'credit_card_info/confirm' => 'credit_card_info#confirm', :as => :confirm_credit_card_info
  match 'subscription', :to => 'home#subscription'

  root :to => 'home#index'

end

app/models/style.rb
class Style < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :videos
  validates_presence_of :name, :description
end

app/controllers/admin/styles_controller.rb
class Admin::StylesController < ApplicationController
	before_filter :authenticate_admin_user!
	def index
		@search = Style.search(params[:q])
    	@styles = @search.result
	end

	def new
	  	@style = Style.new

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @style }
	    end
	end

	def edit
	    @style = Style.find(params[:id])
	end

  	def create
	    @style = Style.new(params[:style])

	    respond_to do |format|
		    if @style.save
		        format.html { redirect_to admin_styles_path, notice: 'style was successfully created.' }
		        format.json { render json: @style, status: :created, location: @teacher }
		    else
		    	format.html {
		    	flash[:alert] = @style.errors.full_messages.join(".\n")
		    	render action: "new" 
		    	}		        
	      	end
	    end
  	end

  	def update
    	@style = Style.find(params[:id])

	    respond_to do |format|
	      	if @style.update_attributes(params[:style])
		        format.html { redirect_to admin_styles_path, notice: 'style was successfully updated.' }
		        format.json { head :no_content }
	      	else
		        format.html { render action: "edit" }
		        format.json { render json: @style.errors, status: :unprocessable_entity }
	      	end
	    end
  	end

  	def destroy
	    @style = Style.find(params[:id])
	    @style.destroy

	    respond_to do |format|
		    format.html { redirect_to admin_styles_path }
		    format.json { head :no_content }
	    end
  	end
  end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  	def show
	  	@current_style_id = params[:id]
	  	@q = Video.search(params[:q])
	  	@videos = @q.result(distinct: true).page(params[:page]).per_page(3).where(:style_id => @current_style_id)
	   	@level = Level.all
	    @style = Style.find(@current_style_id)

	    respond_to do |format|
	      	format.html # show.html.erb
	      	format.json { render json: @style }
	      	format.js
	    end
  	end
end

app/views/styles/_form.html.erb
<%= form_for(@style, :html => { :class => 'form-horizontal'}) do |f| %>
      <% if @style.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

          <ul>
          <% @style.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, :class => "col-lg-2 control-label" %>
        <div class="col-lg-7">
          <%= f.text_field :name, :class => "form-control", :placeholder => "Style Name" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description, :class => "col-lg-2 control-label" %>
        <div class="col-lg-7">
          <%= f.text_area :description, :class => "form-control", :placeholder => "Please write style description", :rows => 10 %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-7">
          <%= link_to "Go back", admin_styles_path, :class => "btn btn-default"%>
          <%= f.submit :class => "btn btn-primary" %>
        </div>
      </div>
<% end%>

app/views/styles/_style_video_list.html.erb
<div class="display_videos_module">
	<%= link_to raw("<span class='txt'>Filter Classes</span><span class='glyphicon glyphicon-chevron-right'></span>"), "#", :id => "class_filter", :class=>"btn buy"%>

    <%= search_form_for(@q, :html => { :class => 'form-inline clearfix', :id => 'video_search_form', :remote =>true}) do |f| %>
	    <div id="search_section">
		    <div class="well search_dark">
	            <div class="row">
		            <div class="col-lg-2">
		            	<p><%= f.label :title_cont,"Search Videos:" %></p>
		            	<%= f.text_field :title_cont, :class => "form-control", :placeholder => "Search Video" %>
		            </div>
		            <div class="col-lg-2">
		            	<p><%= f.label :teacher_id_eq, "Select Teacher" %></p>
		            	<%= f.collection_select( :teacher_id_eq, Teacher.order(:name), :id, :name, {:prompt => "Select a teacher"}, { :class => "form-control"}) %>
		            </div>
		            <div class="col-lg-2">
		            	<p><label>Select Duration</label></p>
		            	<div class="duration_slider"></div> 
		                	<%= f.hidden_field :duration_lteq, :id =>"duration_hidden" %>
		            </div>
		            <div class="col-lg-1">
		            	<p class="duration_min"><span id="duration_slider_result">120</span> min</p>
		            	<%= f.hidden_field :style_id_eq, :value => @current_style_id %>
		            </div>
		            <div class="col-lg-3 level_search">
	        			<p><label>Select Level</label></p>
	        			<% @level.each do |lv| %>
		                  	<input type="checkbox" name="q[level_id_eq_any][]" id="level_id_eq_any_<%= lv.id %>" class="level_eq_search" value="<%= lv.id %>"/>
		                  	<label for="level_id_eq_any_<%= lv.id %>" class="level_buttons">
				                <% x = 1 %>
				               	<% while x <= lv.scale %>
				                    <% x+=1 %>
				                    <span class="glyphicon glyphicon-leaf"></span>
			                    <% end %>
		                  	</label>
		                <% end %>
	        		</div>
		        </div>
		    </div><!--/well-->
		</div>
        <div class="row clearfix" id="video_listing">
        	<%= render 'videos/sorted_videos' %>
        </div><!--/row-->

        <%= f.submit 'Search', :class => "search_submit" %>
    <% end %>
</div>

app/views/styles/index.html.erb
<%= render 'admin/admin/admin_dashboard_tabs', :active_tab => 'dashboard' %>
<div id="dashboard_section" class="admin_dashboard admin_style">
  <div class="inner_container">
    <div id="tabs-1">
    	<%= link_to raw('<span class="glyphicon glyphicon-plus"></span>Add New Style'), new_admin_style_path, :class =>"btn btn-primary pull-right btn-sm add_new_style_btn"%>
      	<h2 class="">Your Listed Styles</h2>
      	<table class="table table-condensed table-striped">
      		<tr>
      			<th>Id</th>
      			<th>Name</th>
      			<th>Description</th>
      			<th>Created at</th>
      			<th>Updated at</th>
      			<th></th>
      		</tr>
      		<% @styles.each do |style| %>
	      		<tr>
	      			<td><%= style.id %></td>
	      			<td><%= style.name %></td>
	      			<td class="description"><%= (truncate h(style.description), 
			                  :length => 300, 
			                  :omission => "...")
			                  .html_safe %></td>
	      			<td><%= nice_date_form(style.created_at) %></td>
	      			<td><%= nice_date_form(style.updated_at) %></td>
	      			<td>
                <%= link_to "Delete", admin_style_path(style), :method => :delete, :confirm =>'Are you sure?', :class => "btn btn-danger btn-sm pull-right" %>
	      				<%= link_to "Edit", edit_admin_style_path(style), :class => "btn btn-warning btn-sm pull-right" %>
	      				
	      				<%= link_to "View", admin_style_path(style), :class => "btn btn-success btn-sm pull-right" %>
	      			</td>
	      		</tr>
      		<% end%>
      	</table>
	</div>
  </div>
</div>

app/views/styles/show.html.erb
<div id="teachers_section">
	<div class="row">
		<div class="col-lg-12">
			<h2 class="teacher_title">Most Recent <%= @style.name %> Classes</h2>
			<p><%= @style.description %></p>
		</div>
	</div><!--/row-->
</div><!--/teachers-section-->

<%= render 'style_video_list' %>