config/routes.rb
DanceDynamics::Application.routes.draw do

  devise_for :users, :controllers => { 
    :registrations => "users/registrations" ,
    :omniauth_callbacks => "omniauth_callbacks"
  }
  devise_scope :user do
    get '/sign_in' => 'sessions#new'
    get "/sign_up", :to => "registrations#new"
  end

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  mount Monologue::Engine, at: '/blog'

 
  get "home/index"
  get "/dashboard" => "users#dashboard", :as => :user_dashboard
  get "/dashboard/profile" => "users#profile", :as => :user_profile
  get "/dashboard/my_classes"  => "users#my_classes", :as => :user_my_classes
  get "users/billing"
  put "users/update_avatar"
  get "users/edit_payment_info"
  get "users/confirm_payment_info"
  get "/register" => "users#new_membership", :as => :new_membership
  post "/payment" => "users#create_membership", :as => :create_membership
  get "users/new_subscription_method"
  get "home/subscription"
  
  resources :styles, :levels, :favorite_videos, :history_videos, :teachers
  resources :favorite_teachers, :only => [:create, :destroy]
  resources :users do
    resources :addresses
    resources :credit_cards
    resources :subscriptions
     post "credit_cards/make_default"
  end
  
  namespace :admin do
    root :to => "admin#index"
    get "/plans" => "admin#plans", :as => :admin_plans do 
      resources :subscriptions
    end
    resources :users
    get "new_admin" => "users#new_admin", :as => :new_admin
    post "create_admin" => "users#create_admin", :as => :create_admin
    get "edit_admin/:id" => "users#edit_admin", :as => :edit_admin
    put "update_admin/:id" => "users#update_admin", :as => :update_admin
    get "new_customer" => "users#new_customer", :as => :new_customer
    post "create_customer" => "users#create_customer", :as => :create_customer
    get "edit_customer/:id" => "users#edit_customer", :as => :edit_customer
    put "update_customer/:id" => "users#update_customer", :as => :update_customer
    resources :videos, :except => [:index]
    resources :today_videos
    get "videos" => "videos#index_admin", :as => :admin_videos
    resources :levels
    resources :styles
    resources :teachers
    resources :users
    resources :comments
    put "/approve_comments" => "comments#approve_comments", :as => :approve_comments
  end
  resources :credit_card_info, :only => [:edit]

  resources :videos do
    resources :comments
  end

  match 'users/confirm_payment_info' => 'users#confirm_payment_info', :as => :confirm_payment_info
  match 'dashboard/billing', :to => 'users#billing'
  match 'credit_card_info/confirm' => 'credit_card_info#confirm', :as => :confirm_credit_card_info
  match 'subscription', :to => 'home#subscription'

  root :to => 'home#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :description,
					  :duration, 
					  :style_id, 
					  :teacher_id,
					  :level_id, 
					  :title,
					  :photo,
					  :wistia_id

	has_attached_file :photo, { 
				:styles => {:medium => "400x400>", :small => "150x150>" },
				:default_url => "http://pixelholdr.com/color:ff5c23/350x246"
				}.merge(PAPERCLIP_STORAGE_OPTIONS)
	            
	# validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg','image/jpg', 'image/png']

	validates_presence_of :description, :duration, :style_id, :teacher_id, :level_id, :title, :wistia_id 

	#relationships
	has_many :comments, dependent: :destroy
	has_many :today_videos, dependent: :destroy
	belongs_to :teacher
	belongs_to :style
	belongs_to :level

	# Favorited by users
	has_many :favorite_videos, dependent: :destroy # just the 'relationships'
	has_many :favorited_by, through: :favorite_videos, source: :user # the actual users favoriting a video
	# Favorited by users
	has_many :history_videos, dependent: :destroy # just the 'relationships'
	has_many :historied_by, through: :history_videos, source: :user # the actual users finish watching a video 

	def calendar
	    @videos = Video.all
	end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_filter :authenticate_admin_user!
 def index_admin
    @search = Video.search(params[:q])
    @videos = @search.result

    @today_video = TodayVideo.new

    @todays = TodayVideo.all
    @videos_by_date = @todays.group_by(&:set_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

  end


  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

   # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to admin_videos_path, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to admin_videos_path, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to admin_videos_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :membership_required

  # GET /videos
  # GET /videos.json
  def index
  # @videos = Video.page(params[:page]).per_page(3)

   @q = Video.search(params[:q])
   @videos = @q.result(distinct: true).page(params[:page]).per_page(3)
   @level_value = ["1","2","3"]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
      format.js
      #  do
      #   @loaded_video = render
      # end
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
    @popular = FavoriteVideo.most_favorite_videos
    @latest_comments = Comment.latest_comment
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
	def get_favorite_video(id)
		@popular_videos = Video.find(id)
		return @popular_videos
	end

	def calendar(date = Date.today, &block)
	    Calendar.new(self, date, block).table
	end

	class Calendar < Struct.new(:view, :date, :callback)
	    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
	    START_DAY = :sunday

	    delegate :content_tag, to: :view

	    def table
	      content_tag :table, class: "calendar" do
	        header + week_rows
	      end
	    end

	    def header
	      content_tag :tr do
	        HEADER.map { |day| content_tag :th, day }.join.html_safe
	      end
	    end

	    def week_rows
	      weeks.map do |week|
	        content_tag :tr do
	          week.map { |day| day_cell(day) }.join.html_safe
	        end
	      end.join.html_safe
	    end

	    def day_cell(day)
	      content_tag :td, view.capture(day, &callback), class: day_classes(day)
	    end

	    def day_classes(day)
	      classes = []
	      classes << "today selected" if day == Date.today
	      classes << "disabled_days disabled" if day < Date.today
	      classes << "notmonth" if day.month != date.month
	      classes.empty? ? nil : classes.join(" ")
	    end

	    def weeks
	      first = date.beginning_of_month.beginning_of_week(START_DAY)
	      last = date.end_of_month.end_of_week(START_DAY)
	      (first..last).to_a.in_groups_of(7)
	    end
	end
end

app/views/admin/videos/_form.html.erb
<div class="inner_container">
    <%= simple_form_for([:admin,@video], :html => { :class => 'form-horizontal'}) do |f| %>
      <% if @video.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>
        </div>
      <% end %>

      <%= f.input :title %>

      <div class="control-group required video_duration">
        <label class="string required control-label" for="video_duration"><abbr title="required">*</abbr>Duration</label>
        <div class="controls">
          <div class="row">
            <div class="col-lg-8">
              <div class="duration_slider"></div> 
              <%= f.hidden_field :duration, :id =>"duration_hidden", :class => "new_slider" %>
            </div>
            <div class="col-lg-3">
              <span class="duration_min" style="display:inline-block;margin-right:5px;"><span id="duration_slider_result">120</span> </span>
              <%= f.error :duration, id: 'duration_error', :style => "color: #b94a48;"  %>
            </div>
          </div>
        </div>
      </div>

      <%=  f.association :style , input_html: { class: 'form-control' }, prompt: "Select your style" %>
      <%=  f.association :teacher , input_html: { class: 'form-control' }, prompt: "Select your teacher" %>
      <%=  f.association :level , input_html: { class: 'form-control' }, prompt: "Select your level" %>
      <%= f.input :wistia_id %>

      <div class="control-group">
        <label class="string required control-label" for="style_name">Upload Video Thumb</label>
        <div class="controls">
          <div class="fileupload fileupload-new" data-provides="fileupload">
            <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                <% if @video.photo.url present? %>
                  <%= image_tag @video.photo.url(:small) %>
                <% else %>
                  <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" />
                <% end %>
              </div>
              <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;">
            </div>
            <div>
              <span class="btn btn-warning btn-file btn-sm">
                <span class="fileupload-new">Select image
                </span>
                <span class="fileupload-exists">Change</span>
                <%= f.file_field :photo %>
              </span>
              <a href="#" class="btn-sm btn btn-danger fileupload-exists" data-dismiss="fileupload">Remove</a>
            </div>
          </div>
        </div>
      </div>

      <%= f.input :description , :input_html => { :rows => 5,:class => "form-control"} %>
      <div class="control-group">
        <label class="string required control-label" for="style_name"></label>
        <div class="controls">
          <%= link_to "Go back", admin_videos_path, :class => "btn btn-default"%>
          <%= f.button :submit, :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div><!--/inner-container-->
</div><!--/gray-box-->

app/views/admin/videos/edit.html.erb
<%= render 'admin/admin_dashboard_tabs', :active_tab => 'videos' %>
<div id="dashboard_section" class="admin_dashboard admin_style">
  <div class="inner_container">
    <div id="tabs-1">
      	<h2> Edit <%= @video.title %></h2>
      	<hr/>
      	<div class="row clearfix">
      		<div class="col-lg-8">
      			<%= render 'form' %>
      		</div>
      	</div>
	</div>
  </div>
</div>

app/views/admin/videos/index_admin.html.erb
<%= render 'admin/admin_dashboard_tabs', :active_tab => 'videos' %>
<div id="dashboard_section" class="admin_dashboard admin_video">
  <div class="inner_container">
    <div id="my_profile" class="dashboard_inner_tab">
      <ul class="class_tabs clearfix">
            <li><a href="#videos">Videos</a></li>
            <li><a href="#set_feature_video">Today's Feature Video</a></li>
        </ul>
        
        <hr/>
      <div id="videos" class="clearfix">
        <div>
          <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>Add New Video'), new_admin_video_path, :class =>"btn btn-primary pull-right btn-sm add_new_style_btn"%>
            <h2 class="">Your Listed Videos</h2>
        </div>
      	
          <%= search_form_for([:admin, @search], :html => { :class => 'form-inline clearfix', :id => 'video_search_form'}) do |f| %>
            <div class="row">
              <div class="col-lg-4"><%= f.text_field :title_cont, :class => "form-control", :placeholder => "Search Video" %>
              </div>
              <div class="col-lg-1">
                <%= f.submit :class =>"btn btn-primary" %>
              </div>
            </div>
          <% end %>
          <% if @videos.count != 0 %>      
          	<table class="table table-condensed table-striped">
          		<tr>
          			<th><%= sort_link @search, :id, "ID" %></th>
          			<th><%= sort_link @search, :title, "Video Name" %></th>
          			<th><%= sort_link @search, :style_id, "Style" %></th>
          			<th><%= sort_link @search, :level_id, "Level" %></th>
          			<th><%= sort_link @search, :teacher_id, "Teacher" %></th>
          			<th class="text-center"><%= sort_link @search, :duration, "Duration" %></th>
                <th class="text-center">Favorited by</th>
                <th class="text-center">Commented by</th>
          			<th><%= sort_link @search, :created_at, "Created on" %></th>
          			<th></th>
          		</tr>
          		<% @videos.each do |video| %>
    	      		<tr>
    	      			<td><%= video.id %></td>
    	      			<td><%= video.title %></td>
    	      			<td><%= video.style.name %></td>
    	      			<td><%= video.level.name %></td>
    	      			<td><%= video.teacher.name %></td>
    	      			<td class="text-center"><%= video.duration %> min</td>
                  <td class="text-center"><%= FavoriteVideo.count :conditions => {:video_id => video.id} %> <span class="glyphicon glyphicon-heart"></span></td>
                  <td class="text-center"><%= video.comments.count %> <span class="glyphicon glyphicon-comment"></span></td>
    	      			<td><%= nice_date_form(video.created_at) %></td>
    	      			<td>
                    <%= link_to "Delete", admin_video_path(video), :method => :delete, :confirm =>'Are you sure?', :class => "btn btn-danger btn-xs pull-right" %>
    	      				<%= link_to "Edit", edit_admin_video_path(video), :class => "btn btn-warning btn-xs pull-right" %>
    	      				
    	      				<%= link_to "View", video_path(video), :class => "btn btn-success btn-xs pull-right" %>
    	      			</td>
    	      		</tr>
          		<% end%>
          	</table>
          <% else %>
            <hr/>
            <h4 class="text-primary">Sorry, there is no videos right now!</h4>
          <% end %>
  	    </div><!--/videos-->
        <div id="set_feature_video" class="clearfix">
          <h2 class="">Featured Videos Schedule</h2>

          <div class="row clearfix">
            <div class="col-lg-8">
              <div id="articles">
                <h2 id="month">
                  <%= link_to "<", date: @date.prev_month, :anchor=>"set_feature_video" %>
                  <%= @date.strftime("%B %Y") %>
                  <%= link_to ">", date: @date.next_month, :anchor =>"set_feature_video" %>
                </h2>
                <%= calendar @date do |date| %>
                  <%= date.day %>
                  <% @videos_by_date['2013-09-16'] %>
                  <% date.to_datetime %>
                  <p>
                    <% if TodayVideo.where(:set_date => date).count > 0 %>
                      <% TodayVideo.where(:set_date => date).each do |set_video| %>
                        <span class="text-primary"><%= set_video.video.title %></span>
                      <% end %>
                    <% end %>
                  </p>
                  <div id="<%= date %>" class="full_hidden_date set"></div>

                <% end %>
              </div>
            </div>
            <div class="col-lg-4" id="display_today_video">
              <h5 class="no_top_margin text-primary">Set a Video for the date: <b><span class="full_date"><%= @date %></span></b></h5>
              <hr/>
              <p id="calendar_form_loader_image"><%= image_tag "loader.gif" %></p>
              <%= simple_form_for [:admin, @today_video],:remote => true do |f| %>
                <%= f.input :set_date ,:as =>:hidden,input_html: { value: @date }%>
                <%= f.association :video ,:label =>"Select a video", :wrapper_html=>{:class => "clearfix"},
                  :as => :radio_buttons
                   %>
                <%= f.button :submit, "Add Video", :class => "btn btn-primary", :id=> "submit_today_video" %>
                <% end %>
            </div>
          </div>
        </div><!--/set_feature_video-->
    </div>
  </div>
</div>

app/views/admin/videos/new.html.erb
<%= render 'admin/admin_dashboard_tabs', :active_tab => 'videos' %>
<div id="dashboard_section" class="admin_dashboard admin_style">
  <div class="inner_container">
    <div id="tabs-1">
      	<h2> Add New Video</h2>
      	<hr/>
      	<div class="row clearfix">
      		<div class="col-lg-8">
      			<%= render 'form' %>
      		</div>
      	</div>
	</div>
  </div>
</div>